### ISSUE TITLE
apache: Allow use of SSLOpenSSLConfCmd DHParameters if supported

### ISSUE THREAD

**Issue by tim-seoss** [mozilla/ssl-config-generator#125]
Versions of Apache > 2.4.8 support:
`SSLOpenSSLConfCmd DHParameters "/path/to/dhparams"`

I think a useful enhancement would be to emit this (if supported) rather than the current:
```
# curl https://ssl-config.mozilla.org/ffdhe2048.txt >> /path/to/signed_cert_and_intermediate_certs_and_dhparams
#SSLCertificateFile      /path/to/signed_cert_and_intermediate_certs_and_dhparams
#SSLCertificateKeyFile   /path/to/private_key
```
Since that's a bit awkward for people to automate if they use automatic SSL cert updating (e.g. via letsencrypt).

**Comment by gstrauss** [comment]
Applications using openssl should prefer `SSL_CTX_set_dh_auto()` and related functions, available since OpenSSL 1.1.0, instead of providing DHParameters.
https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_dh_auto.html

> If "auto" DH parameters are switched on then the parameters will be selected to be consistent with the size of the key associated with the server's certificate. If there is no certificate (e.g. for PSK ciphersuites), then it it will be consistent with the size of the negotiated symmetric cipher key.
> 
> Applications may supply their own DH parameters instead of using the built-in values. This approach is discouraged and applications should in preference use the built-in parameter support described above.

@tim-seoss you might want to open an issue for Apache2 to request that they use `SSL_CTX_set_dh_auto()` or `SSL_set_dh_auto()`

I think that is better than end-users attempting to provide DHParameters (unless end-users know what they are doing and really want to do so).

**Comment by fdelapena** [comment]
Moreover, `SSLOpenSSLConfCmd DHParameters "/path/to/dhparams"` is broken when using recent OpenSSL versions (e.g. 3.x) so it just won't work when just using it. [Apache Users Mailing List thread](https://lists.apache.org/thread/vpqvq8mk9smn0wv749c1ngj09lqbt2wx) and [Qualys Community thread](https://success.qualys.com/discussions/s/question/0D52L00006qPpqqSAC/strange-behavior-dhparam-apache-2451).

By the way, [internet.nl](https://internet.nl/) considers ffdhe2048 phased out on their test and recommends at least ffdhe3072.

**Comment by gstrauss** [comment]
I included the change to use `SSLOpenSSLConfCmd DHParameters "/path/to/dhparams"` in #256, but it is omitted for OpenSSL 3.x where Apache 2.4.52 and later use `SSL_CTX_set_dh_auto()` and `SSL_set_dh_auto()` to follow RFC7919.

Regarding ffdhe3072, that will be reviewed the next time Mozilla updates the ssl-config-generator guidelines.

**Comment by janbrasna** [comment]
I'm considering this be wontfix, and only supporting Apache 2.4.52+ OpenSSL 1.1.0+ API for "auto" RFC7919.

- - - -

> I'm not sure I'm confident to add `SSLOpenSSLConfCmd DHParameters` due to issues mentioned https://github.com/mozilla/ssl-config-generator/issues/125#issuecomment-1382698707 […] before we know more, I wanted to go the opposite way […] skip `DHParameters` entirely, and only make use of the auto params added in the recent versions with #256)

— _Originally posted by @janbrasna in https://github.com/mozilla/ssl-config-generator/issues/257#issuecomment-2407756223_

> Yann Ylavic is an Apache developer and wrote in
> https://lists.apache.org/thread/vpqvq8mk9smn0wv749c1ngj09lqbt2wx
> > Step 3) does not work anymore with latest openssl versions, the only
> way to configure custom dhparams in httpd is to append them to the
> certificate file
> 
> so I'll adjust #256 to not use `SSLOpenSSLConfCmd DHParameters` with OpenSSL 3.x

— _Originally posted by @gstrauss in https://github.com/mozilla/ssl-config-generator/issues/257#issuecomment-2407859729_

> I would prefer to not add the `SSLOpenSSLConfCmd DHParameters` for <2.4.52 […] (Maybe limiting that only to OpenSSL 1.1.0–1.1.1 for those older httpd? Is that extra logic worth maintaining for posterity?)
> 
> Please everyone think about how badly we want to support separate `DHParameters` in Apache 2.4.8–2.4.52 (a ~3 year old release) […] I'd vouch for skipping from appending the params after the certs directly to the auto/RFC feature, leaving out `SSLOpenSSLConfCmd DHParameters` when there are reported issues.

— _Originally posted by @janbrasna in https://github.com/mozilla/ssl-config-generator/issues/257#issuecomment-2407834416_

**Comment by gstrauss** [comment]
> I'm considering this be wontfix, and only supporting Apache 2.4.52+ OpenSSL 1.1.0+ API for "auto" RFC7919.

Even if OpenSSL 1.1.0+ API supports "auto", the apps might not.
In #256, I looked at the *code* in the servers as well as their documentation.  I did not test if "auto" would be passed through, but I did set the version check based on whether the server code would call `SSL_CTX_set_dh_auto()`/`SSL_set_dh_auto()` or not.

**Comment by janbrasna** [comment]
(This issue is for Apache.)

**Comment by gstrauss** [comment]
Due to the (not new) D(HE)ater attack (https://dheatattack.gitlab.io/dheater/), we have chosen (at least for the moment) to continue having the ssl-config-generator recommend appending the 2048-bit FFDHE2048 key to the cert, rather than use DH auto support where available.  Since `SSLOpenSSLConfCmd DHParameters` does not work with OpenSSL 3.x, the change requested in this issue to use `SSLOpenSSLConfCmd DHParameters` would only be for < OpenSSL 3.x, and all those versions before 3.x are EOL.  The is little benefit to changing the output for older versions to use `SSLOpenSSLConfCmd DHParameters`, and then changing back to append the dhparams to the certificate file for use with OpenSSL 3.x, so let's leave it as-is.
