### ISSUE TITLE
Move nginx ssl_protocols directive outside of server context into new parent http context

### ISSUE THREAD

**Issue by gene1wood** [mozilla/ssl-config-generator#141]
Currently the nginx template doesn't assert an [`http`](https://nginx.org/en/docs/http/ngx_http_core_module.html#http) context and just contains [`server`](https://nginx.org/en/docs/http/ngx_http_core_module.html#server) contexts.

In the template's `server` context we assert [`ssl_protocols`](https://github.com/mozilla/ssl-config-generator/blob/924213afb527ccf76c2b0d0185f44a0b17e6f6bd/src/templates/partials/nginx.hbs#L39)

As mentioned in #76 the `ssl_protocols` directive is not actually specific to each vhost. According to https://trac.nginx.org/nginx/ticket/844

> As soon as one host supports a protocol, all the other hosts support that protocol too (even if disabled)

So for clarity (that the `ssl_protocols` is not per vhost) how about we move it out of the `server` context and into a parent `http` context?

We see someone encountering this problem in #140

**Comment by HLFH** [comment]
Thanks @gene1wood!

I have moved in `/etc/nginx/nginx.conf` all these ssl directives within the `http` context:
```
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;  # about 40000 sessions
  ssl_session_tickets off;

  ssl_dhparam /etc/nginx/ssl/dhparam_4096.pem;

  # intermediate configuration
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_ecdh_curve x25519:prime256v1:secp384r1;
  ssl_prefer_server_ciphers off;
```
ssl_ecdh_curve is now working and did not work in the `server` context.
[Nginx documentation is flawed](http://nginx.org/en/docs/http/ngx_http_ssl_module.html) as they still reference both the support of the `http` and the `server` contexts for most of ssl directives.

Furthermore, as I have at least one self-signed TLS certificate, I prefer to keep the OCSP configuration within the`server` context in a file named `ocsp_params` located within the root /etc/nginx configuration folder:
```
  # OCSP Stapling ---
  ssl_stapling on;
  ssl_stapling_verify on;

  resolver 9.9.9.9 valid=300s;
  resolver_timeout 5s;
```

**Comment by makhomed** [comment]
> [Nginx documentation is flawed](http://nginx.org/en/docs/http/ngx_http_ssl_module.html) as they still reference both the support of the `http` and the `server` contexts for most of ssl directives.

Nginx support both the `http` and the `server` contexts for most of ssl directives. Yes, this is true.

Ngixn documentation is not complete reference for all use cases, more information about correct nginx configuration located in nginx trac and nginx maillists.

> At least `ssl_protocols` and `ssl_ecdh_curve` MUST be only located within the `http` context.

No! This is not true. `ssl_protocols` also can be located in the `server` context.

In different IP-based (or port-based) virtual servers are quite possible use different ssl_protocols.

You tries to set different ssl_protocols in name-based virtual
servers. This will not work, because OpenSSL fixes
protocol before the name is known. At the same time, in different
IP-based (or port-based) virtual servers are quite possible
use different ssl_protocols.
 
> And read some interesting comment: [#124 (comment)](https://github.com/mozilla/ssl-config-generator/issues/124#issuecomment-1289968597).

Yes, this is my comment with detailed explain how ssl directives work in the nginx.

I copy text of that my message here:

This is not nginx bugs. Bugs are in your configuration and expectations.

1. You tries to set different ssl_protocols in name-based virtual
servers. This will not work, because OpenSSL fixes
protocol before the name is known. At the same time, in different
IP-based (or port-based) virtual servers are quite possible
use different ssl_protocols.

More about this is here:

https://trac.nginx.org/nginx/ticket/676
https://mailman.nginx.org/pipermail/nginx/2014-November/045738.html

This and other nuances of applying configuration for name-based
virtual servers are documented here:

http://nginx.org/en/docs/http/server_names.html#virtual_server_selection

2. As for TLSv1.3 Ciphersuites, their OpenSSL, apparently, too
selects immediately when the connection is established, and accordingly
it is pointless to set them in name-based virtual servers, it is necessary
set in the default server.

**Comment by gstrauss** [comment]
While @makhomed noted that there are multiple valid ways to express the configuration, the simplest answer for most people is: 

==> Yes, the virtual `server` definitions should be inside an `http` context, and most of the ssl directives should be in the `http` context scope to improve DRYness -- avoid repetition of those directives in each of the virtual servers listening on port 443.  That includes the OCSP directives since most people will either have public certs (with OCSP) or a self-signed cert (without OCSP); much more rarely is there a combination of both.

@HLFH and @makhomed what do you think of PR #277 ?

**Comment by makhomed** [comment]
> > Better to move directive `add_header Strict-Transport-Security "max-age=63072000" always;` to the server context.
> 
> I adjusted that to avoid the non-intuitive behavior, setting `add_header Strict-Transport-Security ...` in each server.

But did you know what if user add to the `server` block any other `add_header` in `server` on any nested `location` context - in such context directive `add_header Strict-Transport-Security ...` will be ton inherited from `http` context level and will be silently dropped?

So, my proposal is to set `add_header Strict-Transport-Security ...` directive inside each `server` block, which listen on the 443 port - and user will explicitly set this header, if need HSTS functionality, and explicitly copy this directive `add_header Strict-Transport-Security ...` in any nested context, if in nested context exists any other `add_header` directives, which disable inheritance from previous configuration level.

From my point of view - non-intuitive behavior is to hide `add_header Strict-Transport-Security "max-age=63072000" always;` directive from user in the `http` context, and expect, what user will remember to copy this directive from `http` context to `server` context, if used add any other `add_header` directives to `server` context or in any nested `location` context.

> I did not move `http2 on;`. While valid in `http` context, putting `http2 on;` in the `http` context could enable h2c (http2 on clear-text ports, e.g. 80), which might allow non-intuitive behavior for the end-user.

But, what is the problem to enable HTTP/2 on the 80 port? Did you see any users, which want to allow HTTP/2 on the 443 port, but need to disable HTTP/2 protocol on the 80 port? What is reason to disable HTTP/2 protocol on the 80 port?

It is no any problem to enable HTTP/2 protocol on the 80 port, if HTTP/2 protocol already enabled on the 443 port. Moreover, in your configuration 80 port has only one server with redirect to 443 port.

It it any [security?] problem, what server does not reject request using HTTP/2 protocol on the 80 port?
 
> Similarly, setting `default_server` for port 443 and rejecting TLS handshake is a strategy which requires SNI for TLS and rejects requests which do not have SNI. Setting `default_server` for port 80 and rejecting connections to the `default_server` requires `Host` header. Both reject requests for unrecognized/unconfigured virtual hosts.

Din you know any modern browsers, which do not sent Host header and do not send SNI when connect to SSL?

If you do not define default_server for 443 port - default_server will be the first server in the list, after alphanumeric sort files in the /etc/nginx/conf.d/ directory. Is it good idea to send all unrecognized requests to this first server on the 443 port?

Today all modern HTTP/HTTPS clients supports both Host header and SNI so it is no problem to drop bad requests.

> `ssl_protocols TLSv1.2 TLSv1.3;`

ancient versions of browsers and HTTP/HTTPS clients, which does not support Host header and SNI - just can't connect to server using modern versions of TLS protocol, TLSv1.2 and TLSv1.3.

Because ancient versions of browsers and HTTP/HTTPS clients know nothing about modern versions of TLS protocol, TLSv1.2 and TLSv1.3.

**Comment by gstrauss** [comment]
> From my point of view - non-intuitive behavior is to hide `add_header Strict-Transport-Security "max-age=63072000" always;` directive from user in the `http` context, and expect, what user will remember to copy this directive from `http` context to `server` context, if used add any other `add_header` directives to `server` context or in any nested `location` context.

Please create a PR with proposed changes and we can discuss the specifics in the PR, though the PR may or may not be accepted.  I do not think this site should include long descriptions of nuances and pitfalls configuring each server, though I would be ok with short (one-line) comments such as something along the lines of "note: add_header must be copied into any sub-context which uses `add_header`"

> But, what is the problem to enable HTTP/2 on the 80 port? Did you see any users, which want to allow HTTP/2 on the 443 port, but need to disable HTTP/2 protocol on the 80 port? What is reason to disable HTTP/2 protocol on the 80 port?

What you do not know can, in fact, hurt you.  And even if it does not hurt you, such a change might still affect others.

Making the change you suggest could cause a behavior change.  As such, I will accept justifications for why this change should be made, if you have any.  I do not consider "I don't understand why not" as a good justification for why a change in behavior *should be* made.

> Din (sic) you know any modern browsers, which do not sent Host header and do not send SNI when connect to SSL?

There are a wide variety of clients, especially with IoT.  "modern browsers" are not the only clients.

**Comment by makhomed** [comment]
> > But, what is the problem to enable HTTP/2 on the 80 port? Did you see any users, which want to allow HTTP/2 on the 443 port, but need to disable HTTP/2 protocol on the 80 port? What is reason to disable HTTP/2 protocol on the 80 port?
> 
> What you do not know can, in fact, hurt you. And even if it does not hurt you, such a change might still affect others.
> 
> Making the change you suggest could cause a behavior change. As such, I will accept justifications for why this change should be made, if you have any. I do not consider "I don't understand why not" as a good justification for why a change in behavior _should be_ made.

You know, how enabling HTTP/2 protocol on the 80 port can hurt you, 
then you already enable HTTP/2 protocol in the nginx on the 443 port?

You say, what directive `http2 on;` in the `http` context is unsafe and can hurt you.

Can you explain more details, why you think, what 
enabling HTTP/2 protocol on the plain TCP socket is dangerous, 
then HTTP/2 protocol already enabled on the 443 port on the TLS socket in the same nginx web server?

**Comment by gstrauss** [comment]
A change in behavior is a change in behavior.  If your log analysis does not expect HTTP/2 via clear-text, then various scripts might get confused.  If parts of your site answering on port 80 do not expect multiple requests being simultaneously processed over HTTP/2, then that can result in unexpected behavior.  If an attacker can cause your site to do something you did not expect, then you might not handle the results properly.

Please use your favorite search engine to look up "Request Smuggling".  Enabling http2 on port 80 where it was not previously enabled can potentially expose an additional attack surface.

I *am not saying* that http2 on port 80 is dangerous.  I *am saying* that *changing existing behavior* can be surprising and I do not want to consider such a change without reasonable justification supporting the change.
