### ISSUE TITLE
Apache rewrite config - double-encoding query strings

### ISSUE THREAD

**Issue by jesusbagpuss** [mozilla/ssl-config-generator#150]
Having deployed the suggested configuration from: https://ssl-config.mozilla.org/#server=apache&version=2.4.6&config=intermediate&openssl=1.0.2k-fips&ocsp=false&guideline=5.6 to a server, I experience double-encoded query-string issue.
 
```apache
<VirtualHost *:80>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well\-known/acme\-challenge/
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>
```
This results in a URL such as:
`http://example.com/cgi/home?screen=EPrint%3A%3AView&id=1234`
being rewritten as:
`https://example.com/cgi/home?screen=EPrint%253A%253AView&id=1234`

Using the '[NE (No Escape)](https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_ne)' flag on the rewrite rule resolves this issue _for my set-up at least_:
`RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,NE,L]`

It may not be as simple as this though - there have been changes in the way Apache/mod_rewrite handled the rewrites over time,   and the 'NE' flag might break other aspects of the URL in older Apache versions (<2.4.1?):
* https://stackoverflow.com/questions/6520484/mod-rewrite-urlencoding-an-already-urlencoded-query-string-parameter-any-way-t
* http://serverfault.com/questions/331899/apache-mod-rewrite-double-encodes-query-string-on-redirect
* https://bz.apache.org/bugzilla/show_bug.cgi?id=34602
* https://bz.apache.org/bugzilla/show_bug.cgi?id=50447

**Comment by gstrauss** [comment]
The Apache mod_rewrite `QSA` flag appends the query string (if present) from the original request URL, so I think that would be more portable.

I propose this incremental improvement for a less-adulterated query string by using the QSA flag:
```
<VirtualHost *:80>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well\-known/acme\-challenge/
    RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R=301,QSA,L]
</VirtualHost>
```

Aside:
`%{REQUEST_URI}` is %-decoded url-path.  Apache mod_rewrite does not expose the original url-path before %-decoding other than in `%{THE_REQUEST}`.   (If someone really needs that before %-decoding they can attempt a regex to pull it out of `%{THE_REQUEST}`.)  I did not look to see what is in `%{THE_REQUEST}` for HTTP/2 requests, which may be different from HTTP/1.x request-line.

**Comment by gstrauss** [comment]
@janbrasna Oracle HTTP is based off of Apache 2.2 (according to https://en.wikipedia.org/wiki/Oracle_HTTP_Server).  The solution applied here in #150 probably can be applied to Oracle HTTP, too, but Oracle HTTP is difficult to work with since they consider basic documentation to be "special" and hidden behind Oracle support account logins, e.g.

Applying Apache Rewrite Rules and Examples to Oracle HTTP Server Configurations (Doc ID 2080577.1)
https://support.oracle.com/knowledge/Middleware/2080577_1.html#REF
> To view full details, sign in with your My Oracle Support account.

If you are able to apply the changes in #150 to oraclehttp.hbs and test against Oracle HTTP, please file a new PR.
