### ISSUE TITLE
HA-Proxy no-sslv3/no-tlsv1x are ignored 

### ISSUE THREAD

**Issue by sachaz** [mozilla/ssl-config-generator#152]
Hello,

On HA-Proxy 2.3.4 I got the following message when I'm applying the ssl-confi-generator configuration:
`Proxy 'https': no-sslv3/no-tlsv1x are ignored for bind '*:443' at [/etc/haproxy/haproxy.cfg:78]. Use only 'ssl-min-ver' and 'ssl-max-ver' to fix. `

So I changed `ssl-default-bind-options prefer-client-ciphers` and `ssl-default-server-options` values to: `no-tls-tickets ssl-min-ver TLSv1.2` (instead of `no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets`)

**Comment by janbrasna** [comment]
Related to #206, will be addressed along with:
- https://github.com/mozilla/ssl-config-generator/issues/206#issuecomment-1867867680

(Will need to differentiate pre-2.2 vs. v2.2+ definitions…)

**Comment by gstrauss** [comment]
@sachaz thank you for the bug report and for providing a solution, as well as reference to the documentation.  I am very sorry that it has taken *years* for this project to respond and to implement the simple fix.  I am a relatively new privileged contributor to this project and will be fixing this shortly.

**Comment by gstrauss** [comment]
For @gene1wood and @janbrasna: if OP was indeed getting error `Proxy 'https': no-sslv3/no-tlsv1x are ignored for bind '*:443' at [/etc/haproxy/haproxy.cfg:78]. Use only 'ssl-min-ver' and 'ssl-max-ver' to fix.`, then ssl-config-generator may have been generating INSECURE configurations for HAProxy for the past 3+ years, for all Old, Intermediate, and Modern, since the config attempt to disable older SSL versions (even `no-sslv3`) was ignored.  I hope that the repetition of the `no-sslv3` in `ssl-default-server-options` covered over this shortcoming in `ssl-default-bind-options`, but I have not tested older ssl-config-generator configurations or older versions of HAProxy since this is now fixed in #275.  However, I am flagging this as an example of ssl-config-generator not being maintained (due to lack of volunteer time) and unfortunately not giving very good configuration advice for a period of years.

**Comment by sachaz** [comment]
> @sachaz thank you for the bug report and for providing a solution, as well as reference to the documentation. I am very sorry that it has taken _years_ for this project to respond and to implement the simple fix. I am a relatively new privileged contributor to this project and will be fixing this shortly.

Thanks for correcting this !
People trust this tool as it has the Mozilla label to get "the best TLS/SSL secure configuration". If the tool is not maintained it should be better to close this service than deliver insecure config.
