### ISSUE TITLE
"Supports …" is weird with non-web servers

### ISSUE THREAD

**Issue by SISheogorath** [mozilla/ssl-config-generator#27]
When generating the configs for postfix or postgresql the indicator still mentions Firefox, Opera and other browsers as supported clients.

![image](https://user-images.githubusercontent.com/8719867/60449614-56c6ba00-9c28-11e9-9e44-2221d8041965.png)

Which, is on the TLS layer might be correct, but practically speaking is complete nonsense.

It would be nice if it would stop doing that and maybe provide email clients like Thunderbird as "Supports …" instead. :smile:

**Comment by april** [comment]
Thanks! This is a bit tricky, because it's difficult to find good data on what clients are compatible with. With web browsers, there's a lot of good information on what cipher suites are supported.

Still, it might be reasonable to at least hide it for non-web servers until I can get better data in there.

**Comment by april** [comment]
I've got this all fixed up, so that field should no longer show for non-webservers.  :)
