### ISSUE TITLE
Tomcat configuration support

### ISSUE THREAD

**Issue by jozefizso** [mozilla/ssl-config-generator#28]
It would be great to get configuration for Tomcat 7, 8 and 9. These are used by Java developers in dev/production environments and it would be helpful to get correct settings for them. Especially as TLS configuration changed a lot between Tomcat 7 and 8.

**Comment by april** [comment]
Do you happen to have any Tomcat 7 and Tomcat 8 configuration files I could build on?

Thanks!  :)

**Comment by sansnom** [comment]
Hi !

There several things to know. Tomcat provides a native library (https://apr.apache.org/) which if enabled will use openssl. If not, SSL will be handle by Java directly. So if APR is not used, SSL capabilities will depends on the Java version (for example TLS 1.3 is only available since Java 11).

The good part is tomcat support openssl syntax for ciphers inside the configuration.

Example with Tomcat 9. Default file with comments removed and added ciphers, honorCipherOrder, and disableSessionTickets:
`<?xml version="1.0" encoding="UTF-8"?>
<Server port="8005" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
  
  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />

  <GlobalNamingResources>
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname="conf/tomcat-users.xml" />
  </GlobalNamingResources>

  <Service name="Catalina">

    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />

    
    
    <Connector port="8443" protocol="org.apache.coyote.http11.Http11AprProtocol"
               maxThreads="150" SSLEnabled="true"
               protocols="all -SSLv3 -TLSv1 -TLSv1.1"
               ciphers="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
               disableSessionTickets="true"
               honorCipherOrder="false">
        <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
        <SSLHostConfig>
            <Certificate certificateKeyFile="conf/localhost-rsa-key.pem"
                         certificateFile="conf/localhost-rsa-cert.pem"
                         certificateChainFile="conf/localhost-rsa-chain.pem"
                         type="RSA" />
        </SSLHostConfig>
    </Connector>

    <Engine name="Catalina" defaultHost="localhost">

      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps" unpackWARs="true" autoDeploy="true">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" prefix="localhost_access_log" suffix=".txt" pattern="%h %l %u %t &quot;%r&quot; %s %b" />
      </Host>
    </Engine>
  </Service>
</Server>
`
The commented connector is the version you should use if APR is disable. Note: you can use this connector with APR enabled and it will openssl for SSL (by default).

References: 
- https://tomcat.apache.org/tomcat-9.0-doc/config/http.html
- https://tomcat.apache.org/tomcat-9.0-doc/config/listeners.html#APR_Lifecycle_Listener_-_org.apache.catalina.core.AprLifecycleListener

**Comment by Mike4Online** [comment]
There are a huge number of applications powered by Apache Tomcat, including many Atlassian applications, so I encourage adding support for it.  

To clarify the previous comment, Apache Tomcat can run with the optional "Tomcat Native" library, which links to the Apache Portable Runtime (APR) library and the OpenSSL library (generally - can also be linked with LibreSSL support).  The changelog for Tomcat Native provides good info about Tomcat Native versions and the various OpenSSL features that are supported.

https://tomcat.apache.org/native-doc/miscellaneous/changelog.html

When Apache Tomcat runs without the Tomcat Native library, it uses the Java JRE for SSL rather than OpenSSL, as mentioned earlier, so the SSL configuration is different.  I'd guess that **Apache Tomcat** and **Apache Tomcat with Tomcat Native Library** would need to be treated as distinct applications for purposes of the Mozilla TLS Configuration Generator.

The changelogs for various versions of Apache Tomcat, e.g. [Apache Tomcat 8.5 changelog](https://tomcat.apache.org/tomcat-8.5-doc/changelog.html) are also helpful.  Within these Tomcat changelogs, changes related to SSL/TLS are generally listed under the category of Coyote (code name for the SSL connector module).

Below is a sample Apache Tomcat configuration file from an Atlassian Jira Software server, with TLS configured in the XML element named **Connector** for port **8443**:

`<?xml version="1.0" encoding="utf-8"?>
<Server port="8005" shutdown="SHUTDOWN">
    <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
    <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
    <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
    <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
    <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
    <Service name="Catalina">
        <Connector port="8080"
                   maxThreads="150"
                   minSpareThreads="25"
                   connectionTimeout="20000"
                   enableLookups="false"
                   maxHttpHeaderSize="8192"
                   protocol="HTTP/1.1"
                   useBodyEncodingForURI="true"
                   redirectPort="8443"
                   acceptCount="100"
                   disableUploadTimeout="true"
                   bindOnInit="false"/>
            <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
              maxHttpHeaderSize="8192" SSLEnabled="true"
              maxThreads="150" minSpareThreads="25"
              enableLookups="false" disableUploadTimeout="true"
              acceptCount="100" scheme="https" secure="true"
              clientAuth="false" sslProtocol="TLS" useBodyEncodingForURI="true"
              keyAlias="tomcat"
              keystoreFile="/opt/atlassian/jira/tomcat-jira-keystore.jks"
              keystorePass="*********"
              keystoreType="JKS"
             />
        <Engine name="Catalina" defaultHost="localhost">
            <Host name="localhost" appBase="webapps" unpackWARs="true" autoDeploy="true">
                <Context path="" docBase="${catalina.home}/atlassian-jira" reloadable="false" useHttpOnly="true">
                    <Resource name="UserTransaction" auth="Container" type="javax.transaction.UserTransaction"
                              factory="org.objectweb.jotm.UserTransactionFactory" jotm.timeout="60"/>
                    <Manager pathname=""/>
                    <JarScanner scanManifest="false"/>
                </Context>
            </Host>
            <Valve className="org.apache.catalina.valves.AccessLogValve"
                   pattern="%a %{jira.request.id}r %{jira.request.username}r %t &quot;%m %U%q %H&quot; %s %b %D &quot;%{Referer}i&quot; &quot;%{User-Agent}i&quot; &quot;%{jira.request.assession.id}r&quot;"/>
        </Engine>
    </Service>
</Server>
`

**Comment by april** [comment]
This was fixed in 8e6c301a835899de5681716e16617e2e55349db1.

https://ssl-config.mozilla.org/#server=tomcat&server-version=9.0.30&config=intermediate

Thanks for everybody's patience on this one!

**Comment by juminda-suurekoerve** [comment]
I had been grateful to find this resource! 
It needed a comma to separate the TLS-versions in the SSLHostConfig block to get it to work for me:
   `protocols="TLSv1.2, TLSv1.3">`
instead of
   `protocols="TLSv1.2 TLSv1.3">`
