### ISSUE TITLE
Intermediate profile produces broken config for old versions of Apache/OpenSSL

### ISSUE THREAD

**Issue by mavit** [mozilla/ssl-config-generator#63]
The `-TLSv1.1` and `-TLSv1.2` options to Apache's `SSLProtocol` directive are available only if you have at least both Apache 2.2.23 and OpenSSL 1.0.1.

The generator already tells people with these versions that their software doesn't support the modern profile.  It should tell them the same for the intermediate profile.

**Comment by april** [comment]
I feel like there's probably a better way to do this, by making a compatible profile? Apache 2.2.23 is seven years old at this point?

Also did you mean to have `-TLSv1.2`? The intermediate profile shouldn't be saying that?

**Comment by mavit** [comment]
> Also did you mean to have `-TLSv1.2`? The intermediate profile shouldn't be saying that?

Sorry, looks like I got carried away.  It's accurate that `-TLSv1.2` needs those versions of Apache and OpenSSL, but it's not relevant to the intermediate profile.

**Comment by april** [comment]
This is very tricky, because I can't have it be `TLSv1.2 TLSv1.3` to this, because that also breaks things. Hmm.

**Comment by gstrauss** [comment]
openssl 1.0.1 supports TLSv1.2.  Earlier versions of openssl do not.  Something like the following (untested) might be a simple fix.
```
--- a/src/js/state.js
+++ b/src/js/state.js
@@ -34,6 +34,9 @@ export default async function () {
   if (minver(configs[server].tls13, form['version'].value) === false || minver(configs['openssl'].tls13, form['openssl'].value) === false) {
     protocols = protocols.filter(ciphers => ciphers !== 'TLSv1.3');
   }
+  if (minver("1.0.1", form['openssl'].value) === false) {
+    protocols = protocols.filter(ciphers => ciphers !== 'TLSv1.2');
+  }
 
   let ciphers = configs[server].cipherFormat ? ssc.ciphers[configs[server].cipherFormat] : ssc.ciphers.openssl;
   if (configs[server].supportedCiphers) {
```
.

I think that if we want Apache to detect its version does not support a given configuration, then that can be done in `src/templates/partials/apache.hbs` since there is no `.tls12` attribute like there is a `.tls13` attribute, and I do not see a huge value in going back through all existing templates to add `.tls12` values.  In the originally posted issue, the statement was that Apache 2.2.23 or later is required for `SSLProtocol`.  As `SSLProtocol` is Apache-specific, logic that displays that to the user (or detects that the configuration will be invalid for versions earlier than Apache 2.2.23), should test for that in `src/templates/partials/apache.hbs`, if detection is desired for incompatibility with such ancient configs.

**Comment by april** [comment]
Unfortunately, I don't think it's worth putting in the development and maintenance effort to generate working configurations for versions of OpenSSL that are over a decade old and haven't been supported in some time. I'd honestly rather have them fail.

And at this point if you can't support TLS 1.2, then quite a lot of the internet is probably broken to you.
