### ISSUE TITLE
Set ECDH curves in Nginx and Apache configuration

### ISSUE THREAD

**Issue by fabian-hk** [mozilla/ssl-config-generator#76]
I am running Nginx 1.17.7 with OpenSSL 1.1.1d and with the configuration from the generator the server supports the ECDH curves ``X448`` and ``secp521r1`` for key exchange in addition to the curves specified in the profile. Shouldn't there be the following line in the Nginx configuration: ``ssl_ecdh_curve X25519:prime256v1:secp384r1;``?

In the Apache configuration, there is the same problem for the version 2.4.41 and OpenSSL 1.1.1d. Shouldn't there be the following line in the configuration: ``SSLOpenSSLConfCmd Curves X25519:prime256v1:secp384r1``?

**Comment by april** [comment]
I haven't been adding curves to the configuration files, because it's very inconsistently supported and because most clients will do the right thing anyways.  :)

**Comment by makhomed** [comment]
> I haven't been adding curves to the configuration files, because it's very inconsistently supported and because most clients will do the right thing anyways. :)

```ssl_ecdh_curve``` now is very inconsistently supported in nginx, because of this is OpenSSL bug.

More details: https://trac.nginx.org/nginx/ticket/1089

```ssl_protocols``` also now supported in nginx very inconsistently due to another OpenSSL bug.

More details: https://trac.nginx.org/nginx/ticket/844

```ssl_ciphers``` also can't be used in nginx for configuring TLS 1.3 ciphers, due to OpenSSL changes.

More details: https://trac.nginx.org/nginx/ticket/1529

**Comment by april** [comment]
It doesn't try to configure those when using TLS 1.3 only.

And I wouldn't say that `ssl_protocols` is "very inconsistently", as tens of thousands of sites have used these configurations successfully. Very few web servers use different protocols for different hostnames, for very good reasons.

**Comment by Mic92** [comment]
> I haven't been adding curves to the configuration files, because it's very inconsistently supported and because most clients will do the right thing anyways. :)

I am currently updating the curves used in NixOS when configuring nginx. 
We currently have `ssl_ecdh_curve secp384r1;` but I thought about extending it to `ssl_ecdh_curve X25519:secp384r1;` https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/nginx/default.nix#L92
Since we control what version of openssl/nginx is used, do you think this is a reasonable approach? From my understanding the inconsistency comes when having different vhosts with different configured curves. This should be not a problem in our case, if we assume that we only have a global curve definition is set that is used for all hosts.

**Comment by Mic92** [comment]
Also should I include `prime256v1` in that case?

**Comment by tomato42** [comment]
If you're fine with enabling X25519 and secp384r1 I really see no reason to exclude prime256v1, especially given that it's one of the best optimised curves in OpenSSL
