### ISSUE TITLE
Intermediate Profile for haproxy does not support Safari 10.1.2 on OSX 10.10.5

### ISSUE THREAD

**Issue by markusweb** [mozilla/ssl-config-generator#79]
i have installed the intermedate profile for haproxy on my server. with this configuration Safari 10.x on OSX 10.10.5 does not work anymore and can't establish a connection. only valid TLS Version is 1.2 as i am still on openssl 1.0.x
i have added TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384  (0xc028) as cipher and now Safari 10.1.2 can connect.

Markus

**Comment by april** [comment]
Huh, it should work with Safari 9, as far as I know. Do you happen to have the list of supported cipher suites for macOS 10.10?

Also, you should generally be careful with running such an old operating system with such an old browser, as there are lots of security vulnerabilities for it.

**Comment by janbrasna** [comment]
Safari 9 running on OSX 10.11 does indeed offer the GCMs, but I suspect the support is limited by OS-level (maybe even the openssl in its darwin I'd guess?) so Safari 10 just running a year older OSX 10.10 might have worse choice of suites.

I don't have any OSX 10.10 around to test, probably just the 10.11s, but will poke around… nonetheless according to 
https://www.ssllabs.com/ssltest/viewClient.html?name=Safari&version=8&platform=OS%20X%2010.10&key=87 _(I know, it's Safari 8, but again, I think the networking is limited OS-side… so Safari 10 on the very same system might be crippled alike)_ it seems all it speaks is the CBCs, nothing more.

_(It's slowly approaching 5 years from its EOL, so that translates to "old" for me, not "intermediate" FWIW.)_

**Comment by janbrasna** [comment]
![safarissl](https://github.com/mozilla/ssl-config-generator/assets/1784648/bbd120b9-8168-468a-8e84-7e5d954237b9)

According to https://en.wikipedia.org/wiki/Version_history_for_TLS/SSL_support_in_web_browsers and references the support is indeed tied to the underlying macOS version, so there's different support profile between:
- Safari **8–10** on OS X **10.10**
and
- Safari **9–11** on OS X **10.11**

Therefore Safari 10 won't connect to intermediate from Yosemite, but will connect from El Capitan or iOS10. That sounds reasonable enough to me.
_(Yosemite is almost 10 years old, and EOLed more that 6 years ago.)_
