### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by nemchik** [mozilla/ssl-config-generator#97]
I would be interested in seeing releases tagged in this repo when the [guidelines](https://github.com/mozilla/ssl-config-generator/tree/master/docs/guidelines) are updated.

**Comment by april** [comment]
I actually tag on the upstream repo for the guidelines:

https://github.com/mozilla/server-side-tls/tags  :)

**Comment by nemchik** [comment]
Lovely! I notice this repo has 5.4 but the upstream repo does not seem to have 5.4 tagged.

I'll subscribe to the upstream repo to receive future updates.

**Comment by janbrasna** [comment]
The [`server-side-tls/tags`](https://github.com/mozilla/server-side-tls/tags) refer to the wiki changes describing the guidelines.

However since the JSON definitions for the guidelines reside in this repo now, I've also tagged the actual spec releases here too, for posterity: [**`ssl-config-generator/tags`**](https://github.com/mozilla/ssl-config-generator/tags) 

_(and will be working on publishing changes to the generated configs/templates in patch releases of this tool itself, too, TBC via #78…)_
